/*
 * CODIGO REALIZADO POR ALVARO ALMANZA.
 * UNIVERSIDAD INTERNACIONAL I DE CASTILLA
 */
package pcdcliente;

import java.io.*;
import java.net.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;


/**
 *
 * @author alvar
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private Socket yo = null;
    private String direccion;
    private int puerto;
    
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        et_ip = new javax.swing.JLabel();
        fi_puerto = new javax.swing.JTextField();
        et_puerto = new javax.swing.JLabel();
        bt_conectar = new javax.swing.JButton();
        fi_ip = new javax.swing.JTextField();
        bt_fichero = new javax.swing.JButton();
        fi_fichero = new javax.swing.JTextField();
        et_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PCDCliente");

        et_ip.setText("IP:");

        et_puerto.setText("Puerto:");

        bt_conectar.setText("Conectar");
        bt_conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_conectarActionPerformed(evt);
            }
        });

        bt_fichero.setText("Seleccionar Archivo");
        bt_fichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ficheroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(et_ip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fi_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(et_puerto)
                        .addGap(18, 18, 18)
                        .addComponent(fi_puerto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_fichero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(bt_conectar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(fi_fichero))))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(et_ip)
                    .addComponent(fi_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fi_puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(et_puerto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_fichero)
                    .addComponent(fi_fichero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_conectar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        et_titulo.setText("Programa Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(et_titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(et_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ficheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ficheroActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        int respuesta = fc.showOpenDialog(this);
        if(respuesta == JFileChooser.APPROVE_OPTION)
        {
            File seleccion = fc.getSelectedFile();
            fi_fichero.setText(fc.getCurrentDirectory()+"\\"+fc.getName(seleccion));
            
        }
    }//GEN-LAST:event_bt_ficheroActionPerformed

    private void bt_conectarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        //implementacion del codigo
        String linea = "";
        BufferedReader fichero = null;
        Comunicacion comunicador = null;
        Escuchar escucha = null;
        Escribir escribe = null;
        
        if (ipvalida(fi_ip.getText()))
        {
            direccion=fi_ip.getText();
        }else
        {
            JOptionPane.showMessageDialog(this,"No Ha introducido una direccion valida");
            fi_ip.setText("");
            fi_puerto.setText("");
            return;
        }
        
        if(puertoValido(fi_puerto.getText()))
        {
            puerto=Integer.parseInt(fi_puerto.getText());
            System.out.println(fi_fichero.getText());
            try {
                fichero = new BufferedReader(new FileReader(fi_fichero.getText()));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
             
            try
            {
                yo = new Socket(direccion,puerto);                
                bt_conectar.setEnabled(false);
                comunicador = new Comunicacion(yo);
                escucha = new Escuchar(comunicador);
                escribe = new Escribir(comunicador, fichero);
                
                escucha.start();
                escribe.start();
            }
            catch (UnknownHostException e)
            {
   		System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this,"Host desconocido");
            } catch (IOException ex) 
            {
                JOptionPane.showMessageDialog(this,"Se ha detectado un error, vuelva a intentarlo de nuevo");
            }
            
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_conectar;
    private javax.swing.JButton bt_fichero;
    private javax.swing.JLabel et_ip;
    private javax.swing.JLabel et_puerto;
    private javax.swing.JLabel et_titulo;
    private javax.swing.JTextField fi_fichero;
    private javax.swing.JTextField fi_ip;
    private javax.swing.JTextField fi_puerto;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    public static boolean ipvalida(String ipAddr)
    {
        boolean valida=false;
        if (ipAddr.equals("localhost"))
        {
            valida=true;
        }else
        {
            Pattern ptn = Pattern.compile("^(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})$");
            Matcher mtch = ptn.matcher(ipAddr);
            valida= mtch.find();
        }
        return valida;
    }
    public static boolean puertoValido(String p)
    {
        int puerto = 0;
        boolean valido=false;
        try{
            puerto = Integer.parseInt(p);
        }catch(NumberFormatException e){
            valido = false;
        }
        if (1024 <= puerto && 65535 >= puerto)
        {
            valido=true;
        }
        return valido;
    }
    public class Comunicacion {
        private Socket cliente = null;
        private BufferedReader entrada = null;
        private DataOutputStream salida = null;
        private Boolean seguir = true;
        
        public Comunicacion (Socket cliente){
            this.cliente = cliente;
            try{
                this.salida = new DataOutputStream(cliente.getOutputStream());
                this.entrada = new BufferedReader(
                    new InputStreamReader(
                        cliente.getInputStream()));                
            }catch(IOException e){
                System.out.println("Error: "+e);
            }
        }
        
        public Boolean leer(){
            int recibo = 0;
            int ack = 5; 
            try{
                while((recibo = this.entrada.read())>=0)
                {
                    if (recibo == ack){
                        return true;
                    }
                }
            }catch(IOException e){
                return false;
            }
            if (recibo != ack)
            {
                return false;
            }
            return true;
        }
        
        public void escribir(String str){
            try{
                for (int i = 0; i < str.length(); i++){
                    this.salida.writeChar(str.charAt(i));
                }
                this.salida.writeChar(-1);
            }catch(Exception e){
            }
        }
        
        public void enviarAck(){
            byte ack = 0x05;
            
            try {
                this.salida.write(ack);
            } catch (IOException ex) {
            }
        }
        
        public void Cerrar(){
            try {
                this.seguir=false;
                this.entrada.close();
                this.salida.close();
                this.cliente.close();
            } catch (IOException ex) {
                
            }
        }
        
        public Boolean getSeguir(){
            return this.seguir;
        }
    }
    
    public class Escuchar extends Thread{
        private Comunicacion comunicador = null;
        
        public Escuchar (Comunicacion cm){
            this.comunicador = cm;
        }
        
        public void run(){
            synchronized (this.comunicador){
                try {
                    this.comunicador.wait();
                    while (this.comunicador.getSeguir()){
                        this.comunicador.leer();
                        this.comunicador.notify();
                        this.comunicador.wait();
                    }
                } catch (InterruptedException ex) {
                    
                }
            }
        }
    }
    
    public class Escribir extends Thread{
        private Comunicacion comunicador = null;
        private BufferedReader fichero = null;
        private String linea = "";
        
        public Escribir(Comunicacion cm, BufferedReader fi){
            this.comunicador = cm;
            this.fichero = fi;
        }
        
        public void run(){
            synchronized (this.comunicador){
                try {
                    while ((linea = fichero.readLine()) != null){
                        this.comunicador.escribir(linea);
                        this.comunicador.notify();
                        this.comunicador.wait();
                    }
                    this.comunicador.enviarAck();
                    this.comunicador.Cerrar();
                    this.comunicador.notify();
                } catch (Exception ex) {
                    
                }
            }
        }
        
    }
}
